Update prometheus ingress
kubecost/cost-analyzer-helm-chart pull request #1127
Opened 2021-11-03 11:30 UTC by korjek

## What does this PR change?
Fix the issue with Prometheus Ingress spec.

## Does this PR rely on any other PRs?
No
- 
- 

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
No impact

## Links to Issues or ZD tickets this PR addresses or fixes

- 
- 

## How was this PR tested?
With `helm update` for running cost-analyzer helm release.

## Have you made an update to documentation?
Not needed

2021-11-03 15:35 UTC, korjek commented
guys, could we add this to 1.88.0 release as well?
This blocks us from upgrading.

2021-11-03 15:54 UTC, AjayTripathy commented
Hi @korjek ... thank you so much for the PR. I'll get it reviewed and see if we can do a 1.88.1 patch release or just re-release 1.88.0

2021-11-03 15:56 UTC, AjayTripathy requested changes

2021-11-03 15:56 UTC, AjayTripathy commented on cost-analyzer/charts/prometheus/templates/server-ingress.yaml
> +                port:
Are we sure about this indent? Isn't port supposed to be outdented here?

2021-11-03 15:57 UTC, AjayTripathy commented
@korjek can you share a subset of the generated YAML file from `helm template` or the prometheus ingress yaml manifest from your testing  ? I'm not sure how this PR would work with the "port" block indented like that.

2021-11-03 20:56 UTC, AjayTripathy approved these changes

2021-11-03 21:08 UTC, merged

2021-11-15 20:11 UTC, AjayTripathy commented
Hi @korjek just letting you know this should be in our staging build but we can't add it retroactively to 1.88.0 

https://github.com/kubecost/docs/blob/main/staging.md for instructions-- otherwise it will be in our next major release. Thanks.