Allow more Prometheus flexibility
kubecost/cost-analyzer-helm-chart pull request #1385
Opened 2022-04-25 11:04 UTC by rlees85

## What does this PR change?
* Allows overriding of Prometheus scrape annotations for Metrics Exporter service.
* Allows overriding of Prometheus scrape annotations for Network Costs service.
* Remove `kubecostMetrics.exporter.annotations` (not used anywhere).
* Adds `ports` declaration in Metrics Exporter deployment.

## Does this PR rely on any other PRs?
N/A 

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
The `prometheus.io/port` annotation is no longer set in the two services mentioned above. This however should not be required as the services only rely on pods/endpoints that have a single port open.

Everything else should behave as before.

## Links to Issues or ZD tickets this PR addresses or fixes
N/A

## How was this PR tested?
- `helm template cost-analyzer --values ...`
- `kubectl apply --dry-run=server -f ...`
- `diff --color ... ...`

## Have you made an update to documentation?
No, `README.md` does not contain a complete list of values anyway - infarct it seems miles off.

## Notes
This is a bit of an awkward one because normally Helm charts do not include Prometheus scrape annotations by default, to allow people to specify their own. However the Kubecost situation is different since it ships with Prometheus by default and is trying to be as light touch as possible (I guess).

To accommodate this I have set defaults that match the current behaviour, but advanced users who want to integrate their own monitoring CAN override the defaults should they wish. Example:

```
###############################################################################

  networkCosts:
    enabled: true
    prometheusScrape: true
    prometheusScrapeAnnotations:
      prometheus.io/scrape: null
      prometheus.io/service-scape-slow: "true"

###############################################################################
```

While I accept this is not perfectly clean I cannot think of a nicer way to achieve this.

If we want to accommodate the port annotations being set (for whatever reason), further changes would be needed to template the custom annotations, since the port value is dynamic (set in values).

I thought of another approach where we could set the annotation tag based off a value instead however this could impact users who are not scraping from annotations at all.

2022-05-02 20:06 UTC, AjayTripathy requested changes

2022-05-02 20:06 UTC, AjayTripathy commented on cost-analyzer/templates/kubecost-metrics-service-template.yaml
> +{{- if .Values.kubecostMetrics.exporter.prometheusScrape }}
This feels like it should have a "kindis" check followed up by a default if not exists to ensure that existing users don't need to modify their values.yaml to make this work. I know that the default is set lower in values.yaml but not all users modify values before upgrading, in which case these labels will be dropped silently.

https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L537

2022-05-02 20:06 UTC, AjayTripathy commented
Hi @rlees85 , very supportive of this change and thank you so much! just one small piece of feedback for backwards compatibility.

2022-06-02 18:59 UTC, nikovacevic reviewed
Seems fine to me. @AjayTripathy want to follow up?

2022-06-10 19:31 UTC, AjayTripathy approved these changes

2022-06-10 19:32 UTC, AjayTripathy commented
Thanks @rlees85 and sorry for the late response. Merging into nightly for further testing!

2022-06-10 19:32 UTC, merged