Add cluster-controller-turndown-config ConfigMap.
kubecost/cost-analyzer-helm-chart pull request #2235
Opened 2023-05-09 23:00 UTC by nik-kc

## Release notes headline
* Adds the ConfigMap for nsturndown, to allow for the frontend to start work on their end.

## Does this PR relate to any other PRs?
* https://github.com/kubecost/cluster-controller/pull/40

## Does this PR address any GitHub or Zendesk issues?
* https://kubecost.atlassian.net/jira/software/c/projects/CORE/boards/1?modal=detail&selectedIssue=CORE-231

## How was this PR tested?
* Tested in new turndown test cluster, verified ConfigMap is created properly and handler returns 200.

2023-05-10 14:22 UTC, ameijer requested changes

2023-05-10 14:22 UTC, ameijer commented on cost-analyzer/templates/kubecost-cluster-controller-template.yaml
> +          name: cluster-controller-turndown-conf
I don't think you need to mount this volume

2023-05-10 14:22 UTC, ameijer commented on cost-analyzer/templates/kubecost-cluster-controller-template.yaml
> +---
This is an interesting approach. I had been thinking that we would just let the mapstore create the object, but this works too. The difference in behavior is that now the configmap is managed by helm, so if the helm release is uninstalled, then this configmap would also be uninstalled since you are creating it here via helm. If you did not create this here, then the mapstore would create it, and it would not be managed by helm so would survive if the helm release was uninstalled. 

I am not sure what the right approach is - do we want the scheduled turndowns to survive a helm uninstall? Helm takes the approach of safety with PVCS, see https://github.com/helm/helm/issues/5156#issuecomment-812963730 ... they are not deleted with a helm delete. What do you think?

2023-05-10 16:10 UTC, nik-kc commented on cost-analyzer/templates/kubecost-cluster-controller-template.yaml
> +          name: cluster-controller-turndown-conf
Thanks for pointing that out, I've updated that.

2023-05-10 16:14 UTC, michaelmdresser commented on cost-analyzer/templates/kubecost-cluster-controller-template.yaml
> +  name: cluster-controller-turndown-config
Please don't use this name. Turndown is already a thing in Cluster Controller and it has a very specific associated with functionality (https://docs.kubecost.com/install-and-configure/advanced-configuration/controller/cluster-turndown), a repository https://github.com/kubecost/cluster-turndown, and a CRD https://github.com/kubecost/cost-analyzer-helm-chart/blob/1723242ea6744b2d20cdda6dea9a4a59ffe22faa/cost-analyzer/templates/kubecost-cluster-controller-template.yaml#L258-L273.

---

We could call it `nsturndown` or `ns-turndown` to disambiguate.

2023-05-10 16:17 UTC, nik-kc commented on cost-analyzer/templates/kubecost-cluster-controller-template.yaml
> +  name: cluster-controller-turndown-config
Fair enough, I'll update the names as such.

2023-05-11 06:23 UTC, nik-kc commented on cost-analyzer/templates/kubecost-cluster-controller-template.yaml
> +---
I can certainly see both sides. Given the comments in that thread, I'd lean towards maintaining the configmap on helm install, but I'm not entirely convinced. I can also see the benefit to removing the configmap, preventing a zombie configmap that may hang around forever, if let unchecked.

2023-05-11 12:18 UTC, ameijer approved these changes

2023-05-11 12:19 UTC, ameijer commented
@michaelmdresser do these changes look good to you?

2023-05-11 15:35 UTC, michaelmdresser approved these changes
LGTM. I'm curious how we'll feel about the ConfigMap choice in a little while; I'm not sure what the right answer is.

2023-05-12 11:17 UTC, merged