Documents ASSET_INCLUDE_LOCAL_DISK_COST
kubecost/cost-analyzer-helm-chart pull request #3449
Opened 2024-06-03 16:06 UTC by thomasvn

## What does this PR change?

- Documents an environment variable. Didn't include a description here because further explanation exists at docs.kubecost.com.

## Does this PR rely on any other PRs?

- Documents https://github.com/opencost/opencost/pull/2441

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

N/A

## Links to Issues or tickets this PR addresses or fixes

N/A

## What risks are associated with merging this PR? What is required to fully test this PR?

N/A

## How was this PR tested?

N/A

## Have you made an update to documentation? If so, please provide the corresponding PR.

N/A

2024-06-04 19:30 UTC, chipzoller requested changes

2024-06-04 19:30 UTC, chipzoller commented on cost-analyzer/values.yaml
> +  #     value: "true"
Can you add a description of what this does and when to use it, please?

2024-06-04 22:56 UTC, thomasvn commented on cost-analyzer/values.yaml
> +  #     value: "true"
Yes, on it!

2024-07-02 18:53 UTC, thomasvn commented
@chipzoller This good to go in?

2024-07-02 19:16 UTC, chipzoller approved these changes

2024-07-03 15:59 UTC, merged