Add SCC for clusterController on OpenShift
kubecost/cost-analyzer-helm-chart pull request #3730
Opened 2024-11-08 20:31 UTC by ivankube

## What does this PR change?
Currently OpenShift users can't add clusterController because of

`W1108 14:19:26.493318   42854 warnings.go:70] would violate PodSecurity "restricted:v1.24": hostPort (container "kubecost-cluster-controller" uses hostPort 9731), allowPrivilegeEscalation != false (container "kubecost-cluster-controller" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "kubecost-cluster-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "kubecost-cluster-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "kubecost-cluster-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`

## Does this PR rely on any other PRs?
No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Add SecurityContext for clusterController when it's enabled on OpenShift

## Links to Issues or tickets this PR addresses or fixes
https://kubecost.atlassian.net/browse/SUP-6255

## What risks are associated with merging this PR? What is required to fully test this PR?
Minimal risks.

## How was this PR tested?
Manually

## Have you made an update to documentation? If so, please provide the corresponding PR.
N/A

2024-12-18 19:46 UTC, thomasvn commented on cost-analyzer/templates/cloud-controller-ocp-scc.yaml
> +  - configMap
```suggestion
volumes:
  - hostPath
  - projected
  - configMap
  - secret
```

According to [SUP-6255](https://kubecost.atlassian.net/browse/SUP-6255) `secret` is required here.

2024-12-18 19:47 UTC, thomasvn commented
@ivankube Generally this looks good! Could you please resolve the merge conflicts here? And can you also provide any documentation you have on how this was tested?

2024-12-18 20:25 UTC, ivankube commented
@thomasvn thank you for the review!

I tested it manually by creating a new local helm chart and using this chart with the Replicated Openshift cluster.

2024-12-18 20:39 UTC, chipzoller requested changes
Please also include an update in the CI workflow [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/.github/workflows/chart.yaml#L184-L190) to enable this new SCC and Cluster Controller.

2024-12-18 21:18 UTC, ivankube commented
@chipzoller https://github.com/kubecost/cost-analyzer-helm-chart/pull/3785

2024-12-18 22:44 UTC, chipzoller commented
Why didn't you just include those changes as part of this PR?

2024-12-19 17:30 UTC, ivankube commented
@chipzoller I've just added the changes to this PR and closed 3785.

2024-12-20 16:42 UTC, chipzoller approved these changes

2024-12-20 21:38 UTC, merged